apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
  labels:
    app: pulsar
    component: pulsar-manager
  name: pulsar-manager
  namespace: default
spec:
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pulsar
      component: pulsar-manager
  serviceName: pulsar-manager
  template:
    metadata:
      labels:
        app: pulsar
        component: pulsar-manager
    spec:
      containers:
      - args:
        - |
          /pulsar-manager/pulsar-manager.sh
        command:
        - sh
        - -c
        image: streamnative/pulsar-manager:0.3.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          tcpSocket:
            port: 7750
          timeoutSeconds: 1
        name: pulsar-manager
        ports:
        - containerPort: 9527
          name: frontend
          protocol: TCP
        - containerPort: 7750
          name: backend
          protocol: TCP
        readinessProbe:
          failureThreshold: 10
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          tcpSocket:
            port: 7750
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 250Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: pulsar-manager-data
        - mountPath: /pulsar-manager/pulsar-manager.sh
          name: pulsar-manager-script
          subPath: entrypoint.sh
        - mountPath: /pulsar-manager/pulsar-backend-entrypoint.sh
          name: pulsar-manager-backend-script
          subPath: backend_entrypoint.sh
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - |
          brokerServiceNumber="$(nslookup -timeout=10 broker | grep Name | wc -l)"; until [ ${brokerServiceNumber} -ge 1 ]; do
            echo "broker cluster pulsar isn't ready yet ... check in 10 seconds ...";
            sleep 10;
            brokerServiceNumber="$(nslookup -timeout=10 broker | grep Name | wc -l)";
          done; echo "broker cluster is ready";
        command:
        - sh
        - -c
        image: streamnative/pulsar-all:2.6.0-sn-21
        imagePullPolicy: IfNotPresent
        name: wait-broker-ready
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - name: pulsar-manager-data
        hostPath:
          path: /mnt/disks/ssd0
      - configMap:
          defaultMode: 493
          name: pulsar-manager-configmap
        name: pulsar-manager-script
      - configMap:
          defaultMode: 493
          name: pulsar-manager-configmap
        name: pulsar-manager-backend-script
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: pulsar-manager-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
        storageClassName: bookie-ssd